server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://192.168.11.200:3306/questions?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: sy
    password: 1dIKOl*T#!Rt
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

